### ISSUE TITLE
关于./react/components/SelectFocusLoad/Types.js中两个方法未找到的问题

### ISSUE THREAD

**Issue by xupengfei2061** [open-hand/test-manager-service#2]
在./react/components/SelectFocusLoad/Types.js中 import { getFoldersByVersion, getLabels } from '../../api/IssueManageApi';   而'../../api/IssueManageApi'未存在这两个方法

**Comment by ethanzhongyi** [comment]
这2个接口在old项目里面有，但是编译后还有很多bug
